### PR TITLE
Add .PHONY to Makefile

### PR DESCRIPTION
**Pull request by PaperMountainStudio**

### CODE REVIEW

**Comment by dylanaraps** [comment]
What is the purpose of this?

**Comment by PaperMountainStudio** [comment]
It is a good practise.
<https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html>

**Comment by dylanaraps** [comment]
Meh. I don't really see the point here. No files named after the targets will ever exist in the repository. Thanks for the PR.

**Comment by dylanaraps** [comment]
Meh. I don't really see the point here. No files named after the targets will ever exist in the repository. Thanks for the PR.

**Pull request closed without merging**
