### PR TITLE
sowm: Border

### PR DESCRIPTION
**Pull request by SeungheonOh**
Patch adding border as requested in #72 

https://github.com/dylanaraps/sowm/pull/74.patch

### CODE REVIEW

**Comment by EnricoMonese** [comment]
Works perfectly, managed to also make it use different colours for some specific programs using `XGetClassHint` and checking `res_class`, is it a good solution or is there a better way to check what program the window belongs to?

**Comment by SeungheonOh** [comment]
That’s a legit way, you can update border-color via XConfiureWindow()

**Comment by huijunchen9260** [comment]
Maybe you need to clean the patch? When I apply the patch, it asks me to apply 2bwm patch blah blah, which is quite annoying.

**Comment by Unixsys** [comment]
Attached for your convience is the transcript of ```printf "pwd $(pwd)\n"; yes | patch -p1 < 74.patch```, where 74.patch was downloaded from the website at approx. 1590525726 (unix timestamp), the sowm repositiory was the latest there was (at the time of writing), and running on a fully patched and updated Arch Linux.

```
pwd /home/usr/sowm
patching file Makefile
patching file README.md
patching file config.def.h
Reversed (or previously applied) patch detected!  Assume -R? [n] y
patching file sowm.c
Hunk #1 FAILED at 8.
Hunk #2 FAILED at 68.
Hunk #3 FAILED at 101.
Hunk #4 FAILED at 108.
Hunk #5 FAILED at 129.
Hunk #6 FAILED at 170.
Hunk #7 FAILED at 210.
Hunk #8 FAILED at 252.
Hunk #9 FAILED at 264.
Hunk #10 FAILED at 284.
Hunk #11 FAILED at 312.
11 out of 11 hunks FAILED -- saving rejects to file sowm.c.rej
The next patch would create the file sowm.h,
which already exists!  Assume -R? [n] y
patching file sowm.h
Hunk #1 FAILED at 1.
Not deleting file sowm.h as content differs from patch
1 out of 1 hunk FAILED -- saving rejects to file sowm.h.rej
The next patch would delete the file patches/.sowm-wheelresize.patch.swp,
which does not exist!  Assume -R? [n] y
File patches/.sowm-wheelresize.patch.swp: git binary diffs are not supported.
patching file patches/sowm-2bswm-style.patch
patching file patches/sowm-almost-tags-0.3.diff
patching file patches/sowm-almost-tags-1.0.diff
patching file patches/sowm-handlebar.patch
patching file patches/sowm-init.patch
patching file patches/sowm-normal-kill.patch
patching file patches/sowm-primitive-multimonitor.patch
patching file patches/sowm-rect-to-move.patch
patching file patches/sowm-rounded-corners.patch
patching file patches/sowm-wheelresize.patch
```

**Comment by Unixsys** [comment]
@EnricoMonese, would you mind sharing your implimentation of what you described? Or is it in a repo somewhere? If so, please point it to me.

**Comment by EnricoMonese** [comment]
@Unixsys basically at line [28 here](https://github.com/dylanaraps/sowm/pull/74/files#diff-094abc45ad7b19a07f10313608f08414R228) the color of the border gets set. This patch has a fixed color, instead of using that directly I first check the class/name of the current window being configured by reading `cl.res_class` or `cl.res_name`. And based on what program it is I choose a desired color.

**Comment by Unixsys** [comment]
@EnricoMonese do you bychance have any idea on how to impliment window border color changes if a window is selected? I tried modifying ```win_focus``` with code to set the border a different color (like the code in ```map_request```), and quickly realized the functions used in ```map_request``` (```XSetWindowBorder``` & ```XConfigureWindow```) required the ```window``` object be passed to it somehow. The ```win_focus``` function gets passed a ```client``` object, but sadly not the ```window``` object. Thus my implimentation failed. :(

**Comment by SeungheonOh** [comment]
I'll close this PR, use the updated one(PR #82 ) instead.

**Pull request closed without merging**
