### PR TITLE
patches: added tj's tags patch

### PR DESCRIPTION
**Pull request by tjtf2**
hi i created a simple patch which allows you to view multiple workspaces at the same time similarly to dwm's tags.

`ctrl+mod+1..6 -> toggle a tag/workspaces from 1->6`
`mod+0 -> enable all tags/workspaces`
(the corresponding keybindings need to be created in your config.h)

the patch is of course not applied by default

to apply the patch do:
`$ patch -p1 < patches/sowm-almost-tags-0.3.diff`

### CODE REVIEW

**Comment by dylanaraps** [comment]
Neat! 

One query: Are you willing to assist in keeping this patch up to date with each tarball release of `sowm`? 

I doubt many releases will be made as core functionality is "done". I picture one more release (`1.0`) will be made sometime this week to fix any bugs that come up and no major releases afterwards. :)

**Comment by tjtf2** [comment]
Thanks for responding!

i'll try to update it as soon as possible with each release

**Comment by dylanaraps** [comment]
Thanks :+1:

**Comment by tjtf2** [comment]
You're welcome and thanks for accepting my patch

**Pull request merged**
