### PR TITLE
New Patch: Rectangular style window launcher/mover + README.md

### PR DESCRIPTION
**Pull request by SeungheonOh**
I've added new patch that allows user to use rectangular style window launching/moving. I'm not sure that this actually called, but here's a [demonstration](https://www.reddit.com/r/unixporn/comments/eah3ak/oc_ive_wrote_sowm_patch_for_rectangle_style/). This patch does not remove original way of window dragging and resizing, It only adds the feature.

I've also added 4th step to Installation section in README.md since I've seen some reddit comments where people don't know how to apply patches.

### CODE REVIEW

**Comment by SeungheonOh** [comment]
By the way, I was amazed by how simple and readable the code was! I really appropriate it.

**Comment by dylanaraps** [comment]
Thanks :+1:

**Comment by Leon-Plickat** [comment]
> I've also added 4th step to Installation section in README.md since I've seen some reddit comments where people don't know how to apply patches.

If you want to prevent confusion and questions by people who don't know how to apply patches, you should probably add that one might have to apply patches manually, if using more than one. Otherwise it is likely that "Patch is broken / won't apply" will become a commonly posted issue.

**Comment by SeungheonOh** [comment]
Oh yeah definitely, I'll make that change as soon as I could!

**Pull request merged**
